model:
  sa:
    radii:
      - - 0.02
        - 0.04
        - 0.08
      - - 0.04
        - 0.08
        - 0.16
      - - 0.08
        - 0.16
        - 0.32
    centers:
      - 2048
      - 512
      - 128
    mlps:
      - - - 32
          - 32
          - 64
        - - 64
          - 64
          - 128
        - - 64
          - 96
          - 128
      - - - 64
          - 64
          - 128
        - - 128
          - 128
          - 256
        - - 128
          - 128
          - 256
      - - - 64
          - 64
          - 128
        - - 128
          - 128
          - 256
        - - 128
          - 128
          - 256
  sa_final:
    mlp:
      - 640
      - 256
      - 512
      - 1024
  fp:
    klist:
      - 3
      - 3
      - 3
    nnlist:
      - - 256
        - 256
      - - 256
        - 128
      - - 128
        - 128
        - 128
  multi:
    pointnet_out_dim: 128
    out_dims:
      - 1
      - 3
      - 3
      - 1
    ps:
      - 0.5
      - 0.7
      - 0.7
      - 0
gripper_depth: 0.035
gripper_width: 0.035
loss:
  conf_mult: 1
  add_s_mult: 10
  appr_vec_mult: 0
  width_mult: 1
data:
  pc_augm:
    occlusion_nclusters: 0
    occlusion_dropout_rate: 0.0
    sigma: 0.000
    clip: 0.005
  depth_augm:
    sigma: 0.001
    clip: 0.005
    gaussian_kernel: 0
  labels:
    num_pos_contacts: 8000
  k: 1
  max_radius: .005
  filter_z: True
  z_val: -0.1
  batch_size: 3
  num_points: 2048
train:
  lr: 0.001

